# Generated by Django 2.2.1 on 2020-01-27 20:32

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('librarybot', '0010_auto_20190302_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('participants', django_mysql.models.SetTextField(models.CharField(max_length=1000), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarybot.ImageUpload')),
            ],
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='token',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='telegram',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='chat',
            name='state',
            field=models.IntegerField(choices=[(0, '<<Idle>>'), (1, '<<Chat ended>>'), (2, '/main'), (3, 'addevent/ask_name'), (4, 'addevent/ask_participants'), (5, 'addevent/end'), (6, 'addevent/ask_name'), (7, 'addevent/ask_sum'), (8, 'addevent/ask_participants'), (9, 'addevent/ask_image'), (10, 'addevent/end'), (11, '/registration/email'), (12, '/registration/end'), (13, '/regbook/ask_name'), (14, '/regbook/ask_author'), (15, '/regbook/ask_language'), (16, '/regbook/ask_hostname'), (17, '/regbook/ask_photo'), (18, '/regbook/ask_isbn'), (19, '/regbook/end'), (20, '/borrow/ask_search'), (21, '/borrow/search_results'), (22, '/borrow/search_result_confirm'), (23, '/borrow/confirm_borrow'), (24, '/borrow/confirm_return')], default=0),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookLanguage',
        ),
    ]
