# Generated by Django 2.2.1 on 2020-01-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarybot', '0012_auto_20200130_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Spendings',
            new_name='Spending',
        ),
    ]
