# Generated by Django 2.2.1 on 2020-01-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarybot', '0013_auto_20200130_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='event',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='participant_number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
